### ISSUE TITLE
Infer schema for remote source 

### ISSUE THREAD

**Issue by zelima** [datahq/planner#19]
As an admin, I want to able to `infer` schema from remote source, without pre-defining it in `flow-spec`, so that I can push datasets to datahub without knowing field names in advance

Eg: I have data remotely that needs to be unpivoted before arriving on datahub. Every time data is updated, new `date` field appears in remote data and I will have to re-define schema every time this happens.

## Acceptance Criteria

* [x] Able to automate pushing CPI to datahub https://github.com/datasets/cpi

## Tasks

* [x] Do analysis

## Analysis 

TODO

**Comment by zelima** [comment]
FIXED/DUPLICATE of https://github.com/datahq/datahub-client/issues/10 
We made it possible to push dataset with `flow.yaml` without defining datapckage.json so above is possible and may be accomplished by knowing which number the header is in the source file. Eg

```
some
extra
text

id,name
1,XXX
```

following `flow.yaml` will give desired result

```
...
processing:
 - 
    input: resoruce-name
   output: resoruce-name 
   tabulator:
     headers: 5
     skip_rows: 4
```
